### ISSUE TITLE
Update the Bar Chart API

### ISSUE THREAD

**Issue by ParrotStone** [recharts/recharts.org#157] opened 2021-01-13 23:01 UTC
Update the Bar Chart API [HERE](https://recharts.org/en-US/api/Bar) -- It describes how to use the label prop in recharts@1.8.5 and not consistent with the modern label usage at major versions@2.x.x.

I hope the whole documentation gets updated & fixed quickly. A lot of JSFiddle iframes are not working as well.

**Comment by avindra** [comment] 2021-01-14 21:10
See #156 for the jsfiddle problem. You can use codesandbox.io in the meantime.

Until then, the examples need to me migrated out of jsfiddle and can only be used from the main site.

**Comment by ParrotStone** [comment] 2021-01-14 23:03
> See #156 for the jsfiddle problem. You can use codesandbox.io in the meantime.
> 
> Until then, the examples need to me migrated out of jsfiddle and can only be used from the main site.

It's not just that the JSFiddle examples are outdated/not-working. The whole documentation hasn't been updated to the latest version. It's actually the documentation of version 1.8.5. It needs to get rewritten.

**Comment by ckifer** [comment] 2022-12-16 05:20
Everything in the docs there seem to be updated to be working as intended to do with the label prop. JSFiddle issue is closes. Closing this

**Closed by ckifer** 2022-12-16 05:20 UTC
